M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu20.04.1} date 2025-01-21T23:34:21+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-21T23:34:21+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X5.212Y-2.806
X5.212Y-2.906
M30
